### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jaykumbhar** [HurinHu/GoogleNews#11]
Didn't get the news data which is available on google
googlenews.clear()

1.googlenews.search('vijay kumbhar')
2.'NoneType' object has no attribute 'get'
3. googlenews.result()
4. []
![newsdata](https://user-images.githubusercontent.com/46997045/72429000-e727af00-37b4-11ea-97a2-818fd5f935b5.PNG)

**Comment by HurinHu** [comment]
Problem solved! Please use `pip install --upgrade GoogleNews` to upgrade to latest version
