### ISSUE TITLE
0 Search Results

### ISSUE THREAD

**Issue by dinahcodes** [HurinHu/GoogleNews#14]
I've tried this a couple of ways but I'm still not getting any search results... any idea what I'm doing wrong here? Code:

```
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('dinosaur')
links = [googlenews.getlinks()]
for link in links:
    print(link)
```

**Comment by mjlabe** [comment]
`getlinks()` should return a list itself, so there is no need to put it in
a list:

`links = [googlenews.getlinks()]`

Should be:

`links = googlenews.getlinks()`

**Comment by dinahcodes** [comment]
Thank you - I tried your suggestion still not getting any results. The code runs without errors and outputs an empty list. Here's what I tried:

```
from GoogleNews import GoogleNews

googlenews = GoogleNews()
googlenews.search('dinosaur')
links = googlenews.getlinks()
print(links)
```

Output: 

`[]`

**Comment by HurinHu** [comment]
I copy your code and run with this result,

['https://www.cnn.com/2020/02/17/world/dinosaurs-eggs-blood-warm-scn/index.html', 'https://scitechdaily.com/disease-found-in-60-million-year-old-dinosaur-tail-that-still-afflicts-humans-today/', 'https://www.theguardian.com/science/2020/feb/10/reaper-of-death-t-rex-dinosaur-species-canada', 'https://www.zmescience.com/science/dinosaur-names-complete-your-vocabulary-with-these-awesome-dinosaurs/', 'https://futurism.com/the-byte/dinosaur-walk-upside-down', 'https://nypost.com/2020/02/17/cancer-seen-in-humans-also-found-in-66-million-year-old-dinosaur-fossil/', 'https://www.foxnews.com/science/dinosaurs-were-warm-blooded', 'https://bgr.com/2020/02/18/dinosaur-prints-cave-ceiling-mystery/', 'https://www.newscientist.com/article/2233396-75-million-year-old-eggshells-suggest-most-dinosaurs-were-warm-blooded/', 'https://nypost.com/2020/02/15/the-top-6-places-in-the-world-to-go-dinosaur-hunting/']

So it should work, please check your network is not behind proxy and google is not block your IP, and update to the latest version of Google News.

Kind Regards,

Hurin Hu
Web Developer
https://hurin.iceloof.com<https://hurin.iceloof.com/>

On 21/02/2020, at 07:51, Dinah J <notifications@github.com> wrote:

print(links)

**Comment by dinahcodes** [comment]
Thank you I will try that and hopefully it will work for me.
