### ISSUE TITLE
Local language

### ISSUE THREAD

**Issue by bestzxcmos03** [HurinHu/GoogleNews#17]
Hello, there's possible to search the news with my language(Thai)?
I've tried to search news with Thai language and it's returned [ ].

**Comment by HurinHu** [comment]
Did you upgrade to last version?

Kind Regards,

Hurin Hu
Web Developer
https://hurin.iceloof.com<https://hurin.iceloof.com/>

On 13/03/2020, at 10:09, itar_ <notifications@github.com> wrote:

﻿

Hello, there's possible to search the news with my language(Thai)?
I've tried to search news with Thai language and it's returned [ ].

**Comment by bestzxcmos03** [comment]
Yes, the latest version is 1.3.4 right?

**Comment by bestzxcmos03** [comment]
Oh, I've just found from your code that the link of news that it's search in time period is for 1 hour only.
What does the ways I can change the time period?

**Comment by HurinHu** [comment]
There is not time period setting here, probably the reason is your local environment encoding, and the result has some different structure.

**Comment by bestzxcmos03** [comment]
https://github.com/HurinHu/GoogleNews/blob/d7990600df0009e9b032381cd69f7edd2aa5ff73/GoogleNews/__init__.py#L37

In this line at "qdr: h" is set to "h".It's mean that in period 1 hour. And i need to change it to "y" (year)
So, how can I do that?

**Comment by HurinHu** [comment]
Just update a new version. you can set the period when you create object or use setperiod() method.

**Comment by bestzxcmos03** [comment]
Thank you. 
Have a nice day.
