### ISSUE TITLE
ImportError: cannot import name 'GoogleNews'

### ISSUE THREAD

**Issue by eabanoz** [HurinHu/GoogleNews#18]
Hi,
I have tried to use the package  like this:
from GoogleNews import GoogleNews
googlenews = GoogleNews()
It gives this error ImportError: cannot import name 'GoogleNews'
PS: I am using Pycharm to load package!

**Comment by shashidharmulakaluri** [comment]
you will need to check if you've installed the package to the right directory using 'pip'.
I'm using anaconda jupyter and using !pip install option, i was to install it and works just fine.

**Comment by mjlabe** [comment]
Any luck? Definitely sounds like a pip or setup issue. Did toy get this resolved?
