### ISSUE TITLE
No result as well

### ISSUE THREAD

**Issue by fabolandry** [HurinHu/GoogleNews#19]
I get an empty list and I checked my network. Something is up

**Comment by mjlabe** [comment]
Code?

**Comment by fabolandry** [comment]
`from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('APPL')
Test = googlenews.gettext()
print(Test)`

**Comment by fabolandry** [comment]
`
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('APPL')
Test = googlenews.gettext()
print(Test)
`

**Comment by fabolandry** [comment]
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('APPL')
Test = googlenews.gettext()
print(Test)

**Comment by mjlabe** [comment]
I am also getting `[]`. I know my contribution to this project (`def get_news(self, deamplify=False)`) broke a couple days ago. It looks like Google has once again changed the format to discourage scraping. This will need to be fixed and is a great opportunity for someone to contribute! ;-)

**Comment by wajihmsedi** [comment]
Same here no results even for Trump. 
@fabolandry @mjlabe @HurinHu you guys have any update ?

**Comment by mjlabe** [comment]
No update here. I've given up on using my contribution because Google breaks it every month.

**Comment by wajihmsedi** [comment]
@mjlabe Pity do you recommend newapi ?

**Comment by mjlabe** [comment]
> @mjlabe Pity do you recommend newapi ?

I'm sure if there is an issue, @HurinHu will fix it, but I thought he pushed an update a few days ago. Have you tried updating? If it's not fixed, take a look at the html you are getting back and compare it to what the project is trying to parse. Should be a quick fix and your contribution would be appreciated. You're going to have this issue with any library that scrapes Google.

**Comment by harkib** [comment]
The API has been working for me the last few days.  Using the following to test;

```
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('tesla')
if googlenews.result() == []:
    print("failed")
else:
    print("passed")
    print(googlenews.get__links())
```

There seems to be some issue of not returning results after heavy use. Documented in; https://github.com/HurinHu/GoogleNews/issues/22
