### ISSUE TITLE
duplicate result

### ISSUE THREAD

**Issue by deviirmr** [HurinHu/GoogleNews#2]
I am getting a duplicate result on page 1

```
googlenews = GoogleNews()
googlenews.search('tailing dam')
googlenews.getpage(1)
news = googlenews.result()
```

Result
![image](https://user-images.githubusercontent.com/10088434/65590521-37bb9800-df8b-11e9-875d-80753e7f7033.png)

Could you please investigate the issue.

**Comment by HurinHu** [comment]
The googlenews.search() will auto fetch the first page, so you don’t need to getpage(1), you can getpage(2) to append second page data.

**Comment by deviirmr** [comment]
Thank you for your reply.
So getpage(3) will apand the results form page 1 + page 2?

**Comment by HurinHu** [comment]
If you use getpage(2) it will get page 1 and 2, if you want to get from page 1 to 3, you need to use getpage(2) and getpage(3), getpage(n) means append nth page to the result.

**Comment by deviirmr** [comment]
Ok, I got it.
This API is very helpful, thank you for creating.
