### ISSUE TITLE
How to set date range

### ISSUE THREAD

**Issue by millorito** [HurinHu/GoogleNews#20]
I am wondering how to set the date range. In the readme it only specifies googlenews.setperiod('d'). What does the 'd' do? How would I be able to specify, for instance, January 1st 2020 until January 2nd 2020? Thanks!

**Comment by Dauflo** [comment]
@millorito Hello 👋

I just start using this lib and asked my self the same question.
After a bit of research (reading source code), i found what 'd' do !

- d: search in last 24h
- h: search last hour
- w: search last week
- m: search last month
- y: search last year

To my knowledge, you cant specify a time frame...
Hope this will help you !
