### ISSUE TITLE
Looking forward to get the news within the specified date range

### ISSUE THREAD

**Issue by ming197** [HurinHu/GoogleNews#23]
I‘m looking forward to the function to get the news within the specified date range, such as the news about covid-19 from 2020.03.01 to 2020.03.30.I think it wiil be more convinient for text analysis.

Thank you for this job!That is great.

**Comment by HurinHu** [comment]
> I‘m looking forward to the function to get the news within the specified date range, such as the news about covid-19 from 2020.03.01 to 2020.03.30.I think it wiil be more convinient for text analysis.
> 
> 
> 
> Thank you for this job!That is great.

Well, I do want to develop this function, unfortunately google is not allowed to search by date range.

**Comment by ming197** [comment]
> > I‘m looking forward to the function to get the news within the specified date range, such as the news about covid-19 from 2020.03.01 to 2020.03.30.I think it wiil be more convinient for text analysis.
> > Thank you for this job!That is great.
> 
> Well, I do want to develop this function, unfortunately google is not allowed to search by date range.

https://www.google.com/search?q=trump&tbas=0&tbs=cdr:1,cd_min:02/01/2020,cd_max:02/10/2020&tbm=nws&sxsrf=ALeKk00Ui4xbdojRFKY_6Rvwwo0jKHoaYg:1587869871088&ei=r_ikXu-CBZ-Hr7wPq5yF4As&start=0&sa=N&ved=0ahUKEwivlvacjIXpAhWfw4sBHStOAbw4ChDy0wMIYA&biw=1280&bih=658&dpr=2

![image](https://user-images.githubusercontent.com/31978733/80309623-cbe32b80-8808-11ea-9a93-f9cb8edee95b.png)

Maybe you can try it!

**Comment by HurinHu** [comment]
> > > I‘m looking forward to the function to get the news within the specified date range, such as the news about covid-19 from 2020.03.01 to 2020.03.30.I think it wiil be more convinient for text analysis.
> > > Thank you for this job!That is great.
> > 
> > 
> > Well, I do want to develop this function, unfortunately google is not allowed to search by date range.
> 
> https://www.google.com/search?q=trump&tbas=0&tbs=cdr:1,cd_min:02/01/2020,cd_max:02/10/2020&tbm=nws&sxsrf=ALeKk00Ui4xbdojRFKY_6Rvwwo0jKHoaYg:1587869871088&ei=r_ikXu-CBZ-Hr7wPq5yF4As&start=0&sa=N&ved=0ahUKEwivlvacjIXpAhWfw4sBHStOAbw4ChDy0wMIYA&biw=1280&bih=658&dpr=2
> 
> ![image](https://user-images.githubusercontent.com/31978733/80309623-cbe32b80-8808-11ea-9a93-f9cb8edee95b.png)
> 
> Maybe you can try it!

Thanks for your link, I have add this to the latest version, you can upgrade the package with `pip install --upgrade GoogleNews`
