### ISSUE TITLE
Options for 'period' parameter

### ISSUE THREAD

**Issue by silviacamplani** [HurinHu/GoogleNews#29]
Are the following options suitable for the period parameter? If not, are there other options rather than 'd'?
'h': past hour.
'd': past 24 hours.
'7d': past week.
'm': past month.
'1y': past year.

I got them on the google news website but when I use 7d or m I retrieve only news of the current day or more than 7 days/month old...

**Comment by HurinHu** [comment]
h (past hour)
d (past day)
w (past week)
m (past month)
y (past year)
 
You can specify intermediate time periods by adding a number:
h12 (past 12 hours)
d3 (past 3 days)
w2 (past 2 weeks)
m6 (past 6 months)
