### ISSUE TITLE
How to get full news article

### ISSUE THREAD

**Issue by gmehta1996** [HurinHu/GoogleNews#30]
Is there a way to get the entire news article text from this or even an entire paragraph containing that particular keyword as currently we can get just 1 or 2 lines followed by '...' ??
For ex.   'Description': "Jio's parent Reliance Industries (RIL)\u2060, a conglomerate with businesses ranging from oil and petrochemicals to technology, retail and telecom\u2060, is less than a ..."

Is there a way to get full description???

**Comment by HurinHu** [comment]
No, when you search on news.google.com, you can't get full description either, it only can show partial description, if you want to get more, you can visit the link on each news.
