### ISSUE TITLE
Is the API still functioning

### ISSUE THREAD

**Issue by harkib** [HurinHu/GoogleNews#31]
I used the API extensively for a few months. I came back it to it today after a few weeks and seem to not be returning any results. I could be blocked by some server on the way. Is the API still working for others?

Code used for test.
```
from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('tesla')
if googlenews.result() == []:
    print("failed")
else:
    print("passed")
    print(googlenews.get__links())
```

**Comment by HurinHu** [comment]
Yes, it is still working. I think your IP is being block by Google.
