### ISSUE TITLE
languages settings

### ISSUE THREAD

**Issue by jasonxu1991** [HurinHu/GoogleNews#4]
Hi HurinHu, great work!  I was wondering if i can set the language of the google news im fetching, Thanks !

**Comment by HurinHu** [comment]
This is based on your PC default language setting. You can search keywords in any language, the result and format you see will be same as you use google search in browser.

**Comment by h3artofeverything** [comment]
Hello HurinHu, thank you for this! 
Could I ask if I search japanese characters, will it default it to google.co.jp results? 
I wasn't able to search with japanese characters. 

Thank you!

**Comment by HurinHu** [comment]
I think the result will be same, it seems only support English at this moment. I will implement it to support other language later.

Kind Regards,

Hurin Hu
Web Developer
https://hurin.iceloof.com<https://hurin.iceloof.com/>

On 25/02/2020, at 21:24, h3artofeverything <notifications@github.com> wrote:

﻿

Hello HurinHu, thank you for this!
Could I ask if I search japanese characters, will it default it to google.co.jp results?
I wasn't able to search with japanese characters.

Thank you!

**Comment by HurinHu** [comment]
It is already fixed in the latest version.
