### ISSUE TITLE
Empty list always returned

### ISSUE THREAD

**Issue by akeklak** [HurinHu/GoogleNews#5]
Hi,

Thanks for making this module.  Unfortunately, I only get empty lists returned when trying to make searches.  Any thoughts to what the issue might be?  I've tried the basic example below:

from GoogleNews import GoogleNews
googlenews = GoogleNews()
googlenews.search('APPL')
news = googlenews.result()
print(news)

**Comment by HurinHu** [comment]
"from GoogleNews import GoogleNews" not "import GoogleNews from GoogleNews"
and it will gets result. If you run code behind proxy, please remember set the proxy in code for network request.

**Comment by akeklak** [comment]
Sorry, that was a typo (and would also return a syntax error, it's not the issue).  I'm just running the script directly from my laptop, and do not have any proxy servers configured.

**Comment by HurinHu** [comment]
Well, I have tried it again, it works. The problem might be your environment, if your public ip doing to much things and google need to verify you are not robot, try to open google on you browser and check it right or not.

**Comment by akeklak** [comment]
I am able to access google in my browser, and tried using the format of the URL contained in the self.url variable (self.url="https://www.google.com/search?q="+self.key+"&tbm=nws&start=%d") with "+self.key+" replaced by my search term, and the search is successful.  Any other thoughts on how to troubleshoot?  Thanks again.

**Comment by HurinHu** [comment]
No idea about that, the only issue I found is google trying to verify you are not robot.

**Comment by akeklak** [comment]
Ok.  I will try it out from a hosted virtual linux machine instead, hopefully that works.  In general, what does it take for Google to classify you as a robot using this API?  I.e., is it a number of search requests per day, or a certain number in very quick succession?  Thanks again for the help!

**Comment by HurinHu** [comment]
mostly it will depends on your public IP, like if you are doing it on your VPS or send several request within a second , it will be a big chance to have this issue

**Comment by akeklak** [comment]
Ok, I'll add some time delays in my script then.  Gonna close the issue now - thanks one last time!

**Comment by Q-Tran** [comment]
Also having the same issue. Added delays and same result occurred. Went to google news and entering the data manually was fine.
