### ISSUE TITLE
How to get complete article description (instead of first few sentences)

### ISSUE THREAD

**Issue by Mayank-Bhatia** [HurinHu/GoogleNews#6]
Currently the `getpage` method shows something like:
```
[{
'title': "Endgame: It's Amazing That No One Died In Thanos ...", 
'media': 'Screen Rant', 
'date': 'Dec. 2, 2019', 
'desc': 'Avengers: Infinity War saw most of the superheroes in the MCU fight Thanos and his armies on Earth and outer space – but the Mad Titan won\xa0...',
'link': 'https://screenrant.com/avengers-endgame-thanos-attack-no-one-died-how/',
'img': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL__t6M0yeasih6JxReLAF1ilEcVstSQd3t-0zrGIL71-FNIeQsqCX9KiRdDuqIK17M_feDUX9&s'
}]
```

Is there any way to get the complete description with this package?

Thanks in advance!

**Comment by HurinHu** [comment]
Hi, this text is getting from https://news.google.com/ and the search result only provide partial description as you search on google news website. Can't get the full description at this moment.

**Comment by Mayank-Bhatia** [comment]
That's understandable. Is there anyway to get the labels/keywords associated to the articles?

**Comment by mjlabe** [comment]
I'd mark this as "won't fix" and close the issue since it is beyond the scope of scraping Google News.
